name: Deploy lambda

on: 
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy lambda
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: '3.10'
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m venv lambda
          source lambda/bin/activate
          
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
          zip lambda.zip main.py
          mv lambda.zip lambda/lib/python3.9/site-packages/
          listaArchivos=`ls`
          zip -r lambda.zip $listaArchivos

          ls -l
