name: Deploy lambda

on: 
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  build:
    name: Deploy lambda
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: '3.8' 
    - name: Package
      run: |
          python -m pip install --upgrade pip
          python -m venv lambda
          source lambda/bin/activate
          
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          
          zip lambda.zip main.py
          mv lambda.zip lambda/lib/python3.8/site-packages/
          listaArchivos=`ls`
          zip -r lambda.zip $listaArchivos
  
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Send to lambda
    - uses: appleboy/lambda-action@v0.1.5
    - with:
        aws_access_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws_region: ${{ secrets.AWS_REGION }}
        function_name: main
        source: put_objects_image_repo/Lib/site-packages/lambda.zip
