name: Deploy lambda

on: 
  push:
    branches: [ dev ]

  workflow_dispatch:

jobs:
  deploy:
    name: Deploy lambda
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Package
        run: |
          sudo apt update
          sudo apt install software-properties-common
          sudo add-apt-repository ppa:deadsnakes/ppa
          sudo apt install python3.9
          sudo apt install python3.9-dev python3.9-venv

          python3.9 -m venv lambda
          source lambda/bin/activate
          pip install -r requerimients.txt
          
          cd src
          zip lambda.zip main.py
          mv lambda.zip Lib/site-packages/
          cd Lib/site-packages/
          listaArchivos=`ls`
          zip -r lambda.zip $listaArchivos

          ls
